services:
  - type: web
    name: formengine-pro
    env: node
    repo: https://github.com/CHAMA18/formengine-pro
    branch: main
    buildCommand: bash scripts/render-build.sh
    startCommand: bash scripts/render-start.sh
    healthCheckPath: /
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: formengine-pg
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: formengine-pg
    databaseName: formengine
    databaseUser: fep
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
